// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disabled': string;
  'enabled': string;
  'error': string;
  'footer': string;
  'legendItem': string;
  'legendItemColor': string;
  'redirected': string;
  'statistics': string;
}
export const cssExports: CssExports;
export default cssExports;
