// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'categories': string;
  'date': string;
  'details': string;
  'elapsedTime': string;
  'indexer': string;
  'parametersContent': string;
  'query': string;
  'releaseGroup': string;
  'source': string;
}
export const cssExports: CssExports;
export default cssExports;
