// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'example': string;
  'footNote': string;
  'isFullFilename': string;
  'large': string;
  'option': string;
  'small': string;
  'token': string;
}
export const cssExports: CssExports;
export default cssExports;
