// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonContainer': string;
  'buttonContainerContent': string;
  'buttons': string;
  'grabReleasesButton': string;
  'indexerContainer': string;
  'inputContainer': string;
  'searchButton': string;
  'selectedReleasesLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
