// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addApplication': string;
  'applications': string;
  'center': string;
}
export const cssExports: CssExports;
export default cssExports;
