// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'added': string;
  'appProfileId': string;
  'capabilities': string;
  'id': string;
  'minimumSeeders': string;
  'packSeedTime': string;
  'priority': string;
  'privacy': string;
  'protocol': string;
  'seedRatio': string;
  'seedTime': string;
  'sortName': string;
  'status': string;
  'tags': string;
  'vipExpiration': string;
}
export const cssExports: CssExports;
export default cssExports;
