// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteButton': string;
  'description': string;
  'modalFooter': string;
  'selectedTab': string;
  'tab': string;
  'tabContent': string;
  'tabList': string;
  'tabs': string;
}
export const cssExports: CssExports;
export default cssExports;
