// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addIndexerProxy': string;
  'center': string;
  'indexerProxies': string;
}
export const cssExports: CssExports;
export default cssExports;
