// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addAppProfile': string;
  'appProfiles': string;
  'center': string;
}
export const cssExports: CssExports;
export default cssExports;
