// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'container': string;
  'content': string;
  'downloadIcon': string;
  'downloadLink': string;
  'indexerRow': string;
  'info': string;
  'infoRow': string;
  'interactiveIcon': string;
  'manualDownloadContent': string;
  'title': string;
  'titleRow': string;
}
export const cssExports: CssExports;
export default cssExports;
