// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'details': string;
  'elapsedTime': string;
  'parametersContent': string;
  'query': string;
  'source': string;
}
export const cssExports: CssExports;
export default cssExports;
