// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alert': string;
  'filterContainer': string;
  'filterInput': string;
  'filterLabel': string;
  'filterRow': string;
  'indexers': string;
  'modalBody': string;
  'scroller': string;
}
export const cssExports: CssExports;
export default cssExports;
