// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alreadyExistsIcon': string;
  'protocol': string;
}
export const cssExports: CssExports;
export default cssExports;
