using System.Collections.Generic;
using FluentValidation;
using NzbDrone.Core.Annotations;
using NzbDrone.Core.Indexers;
using NzbDrone.Core.Validation;

namespace NzbDrone.Core.Applications.LazyLibrarian
{
    public class LazyLibrarianSettingsValidator : AbstractValidator<LazyLibrarianSettings>
    {
        public LazyLibrarianSettingsValidator()
        {
            RuleFor(c => c.BaseUrl).IsValidUrl();
            RuleFor(c => c.ProwlarrUrl).IsValidUrl();
            RuleFor(c => c.ApiKey).NotEmpty();
        }
    }

    public class LazyLibrarianSettings : IApplicationSettings
    {
        private static readonly LazyLibrarianSettingsValidator Validator = new LazyLibrarianSettingsValidator();

        public LazyLibrarianSettings()
        {
            ProwlarrUrl = "http://localhost:9696";
            BaseUrl = "http://localhost:5299";
            SyncCategories = new[] { 3030, 7000, 7010, 7020, 7030, 7040, 7050, 7060 };
        }

        public IEnumerable<int> SyncCategories { get; set; }

        [FieldDefinition(0, Label = "Prowlarr Server", HelpText = "Prowlarr server URL as LazyLibrarian sees it, including http(s)://, port, and urlbase if needed")]
        public string ProwlarrUrl { get; set; }

        [FieldDefinition(1, Label = "LazyLibrarian Server", HelpText = "LazyLibrarian server URL, including http(s):// and port if needed")]
        public string BaseUrl { get; set; }

        [FieldDefinition(2, Label = "ApiKey", Privacy = PrivacyLevel.ApiKey, HelpText = "The ApiKey generated by LazyLibrarian in Config/Interface")]
        public string ApiKey { get; set; }

        public NzbDroneValidationResult Validate()
        {
            return new NzbDroneValidationResult(Validator.Validate(this));
        }
    }
}
