// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'age': string;
  'category': string;
  'files': string;
  'grabs': string;
  'indexer': string;
  'indexerFlags': string;
  'peers': string;
  'protocol': string;
  'size': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
