// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'age': string;
  'category': string;
  'cell': string;
  'checkInput': string;
  'downloadIcon': string;
  'downloadLink': string;
  'externalLinks': string;
  'files': string;
  'grabs': string;
  'indexer': string;
  'indexerFlags': string;
  'interactiveIcon': string;
  'manualDownloadContent': string;
  'peers': string;
  'protocol': string;
  'size': string;
  'sortTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
